@startuml

'-----------------------------------------------------------

class 자동납부_DAO {
  + 자동납부조회(사용자VO) : 납부내역VO
  + 자동납부신청(사용자VO, 납부내역VO) : 결과VO
  + 자동납부변경(사용자VO, 납부내역VO) : 결과VO
  + 자동납부해지(사용자VO) : 결과VO
}

interface 자동납부_Service {
  + 자동납부조회(사용자VO) : 납부내역VO
  + 자동납부신청(사용자VO, 납부내역VO) : 결과VO
  + 자동납부변경(사용자VO, 납부내역VO) : 결과VO
  + 자동납부해지(사용자VO) : 결과VO
}

class 자동납부_ServiceImpl {
  + 자동납부조회(사용자VO) : 납부내역VO
  + 자동납부신청(사용자VO, 납부내역VO) : 결과VO
  + 자동납부변경(사용자VO, 납부내역VO) : 결과VO
  + 자동납부해지(사용자VO) : 결과VO
  + 자동납부신청이력저장(사용자VO, 납부내역VO) : 결과VO
}

자동납부_Service <|.. 자동납부_ServiceImpl
자동납부_DAO <.. 자동납부_ServiceImpl

납부내역VO <.. 자동납부_ServiceImpl
사용자VO <.. 자동납부_ServiceImpl
결과VO <.. 자동납부_ServiceImpl


class 자동납부_Controller {
  + 자동납부조회(사용자VO) : List<납부내역VO>
  + 자동납부신청(사용자VO, 납부내역VO) : 결과VO
  + 자동납부변경(사용자VO, 납부내역VO) : 결과VO
  + 자동납부해지(사용자VO) : 결과VO
}

자동납부_ServiceImpl <.. 자동납부_Controller

class 공통VO {
  + CP 인증정보
  + 사용자 ID
  + 조직 ID
  + 채널 구분
  + Source ID
  + 시스템발급일련번호
  + 시스템내구간순서
}
class 납부내역VO {
  + 청구사용자 key
  + 청구년월
  + 납부요청일련번호 
  + 납부방법
  + 납부타입
  + 납부상세1
  + 납부상세2
  + 납부상세3
  + 납부요청 금액
  + 납부한 금액
  + 수수료타입
  + 수수료
  + 수수료세금
  + 변경일
  + 납부일시
}
class 사용자VO {
  + 사용자 CI
  + 사용자 이름
  + 사용자 전화
}
class 결과VO {
  + 오류코드
  + 오류설명
  + 결과코드
  + 결과설명
}

'-----------------------------------------------------------

@enduml
