@startuml

actor 외부채널고객
participant 포인트허브
participant 클립포인트
participant SHUB

'중복거래체크
'프로세스 진행중 요청정보 업데이트 확인

외부채널고객 -> 포인트허브 ++ : K포인트조회
note right : K포인트 조회 API\n(외부체널 -> 포인트허브) 사용
포인트허브 -> 포인트허브 : 외부 I/F 이력생성
포인트허브 -> 클립포인트 ++ : K포인트조회요청
note right : K포인트 조회 모듈\n(포인트허브 -> 클립포인트) 사용\n클립포인트 I/F 이력처리
return K포인트
포인트허브 -> 포인트허브 : 외부 I/F 이력갱신
return K포인트

외부채널고객 -> 포인트허브 ++ : 회선선택(납부)
note right : 통신료 납부 API\n(외부체널 -> 포인트허브) 사용
포인트허브 -> 포인트허브 : 외부 I/F 이력생성
포인트허브 -> 포인트허브 : 임시원장생성

포인트허브 -> 클립포인트 ++ : 포인트차감요청
note right : K포인트 차감 모듈\n(포인트허브 -> 클립포인트) 사용\n클립포인트 I/F 이력처리
return 차감결과

포인트허브 -> SHUB ++ : 납부요청
note right : 통신료 납부 API\n(포인트허브 -> SHUB) 사용\nSHUB I/F 이력처리
return 납부결과

alt 납부성공
  포인트허브 -> 포인트허브 : 납부원장생성
else 납부실패
  포인트허브 -> 클립포인트 ++ : 포인트차감취소요청
  note right : K포인트 차감취소 모듈\n(포인트허브 -> 클립포인트) 사용\n클립포인트 I/F 이력처리
  return 차감취소결과
end

포인트허브 -> 포인트허브 : 임시원장갱신(납부결과)

포인트허브 -> 포인트허브 : 외부 I/F 이력갱신
return 납부결과

@enduml
